# Dummy RC file: the real one is generated by the FreeCAD build system. To use Qt resources in your
# module you MUST import this RC file. Do not add *this* file to the cMake system, it only exists
# to explain the "import AddonManager_rc" line (and to silence the linter about the missing import).
